title: Hey there, I'm George!
description: > # this means to ignore newlines until "baseurl:"
 Personal website
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: George Kousis # add your name
author-img: avatar.jpg # add your photo
author-cv: cv-george-kousis.pdf # a cv file
about-author: I am an electrical and computer engineer! Welcome to a personal web page with some of my projects. # add description
social-twitter: gmkroute # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: kusius # add your Github handle
social-linkedin: george-kousis # add your Linkedin handle
social-email: gmkousis@gmail.com  # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
